package com.example.hotel.entity;


import cn.afterturn.easypoi.excel.annotation.Excel;

import cn.afterturn.easypoi.excel.annotation.ExcelEntity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.Date;
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })

public class Orders implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    @Excel(name = "订单编号",width = 20)
    private Integer orderid;
    @Excel(name = "房间编号",width = 20)
    private  Integer roomid;
    @Excel(name = "用户编号",width = 20)
    private  Integer userid;
    @Excel(name = "价格",width = 20)
    private  Integer price;
    @ExcelEntity
    private User user;
    @Excel(name = "房间号码",width = 20)
    private  String number;
    @Excel(name = "房型名字",width = 20)
    private  String roomtypename;
    @Excel(name = "预定日期",width = 20)
    private Date bookdate;

    @Excel(name = "入住日期",width = 20)
    private Date checkindate;

    @Excel(name = "离开日期",width = 20)
    private Date leavedate;

    @Excel(name = "是否付款",width = 20)
    private String state;


    @Excel(name = "备注",width = 20)
    private String message;

    public Orders() {
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getRoomtypename() {
        return roomtypename;
    }

    public void setRoomtypename(String roomtypename) {
        this.roomtypename = roomtypename;
    }

    public Integer getRoomid() {
        return roomid;
    }

    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderid
     *
     * @return the value of orders.orderid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderid
     *
     * @param orderid the value for orders.orderid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }


    public Date getBookdate() {
        return bookdate;
    }

    public void setBookdate(Date bookdate) {
        this.bookdate = bookdate;
    }

    public Date getCheckindate() {
        return checkindate;
    }

    public void setCheckindate(Date checkindate) {
        this.checkindate = checkindate;
    }

    public Date getLeavedate() {
        return leavedate;
    }

    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.message
     *
     * @return the value of orders.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.message
     *
     * @param message the value for orders.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    @Override
    public String toString() {
        return "Orders{" +
                "orderid=" + orderid +
                ", roomid=" + roomid +
                ", userid=" + userid +
                ", user=" + user +
                ", number='" + number + '\'' +
                ", roomtypename='" + roomtypename + '\'' +
                ", bookdate='" + bookdate + '\'' +
                ", checkindate='" + checkindate + '\'' +
                ", leavedate='" + leavedate + '\'' +
                ", state='" + state + '\'' +
                ", message='" + message + '\'' +
                '}';
    }
}