package com.example.hotel.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
public class Roomtype implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.roomtypeid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer roomtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.roomtypename
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String roomtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.price
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.capacity
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.bed
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer bed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.roomnumber
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.Booked
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer booked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.Checkedin
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer checkedin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.roomtypeid
     *
     * @return the value of roomtype.roomtypeid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getRoomtypeid() {
        return roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.roomtypeid
     *
     * @param roomtypeid the value for roomtype.roomtypeid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setRoomtypeid(Integer roomtypeid) {
        this.roomtypeid = roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.roomtypename
     *
     * @return the value of roomtype.roomtypename
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getRoomtypename() {
        return roomtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.roomtypename
     *
     * @param roomtypename the value for roomtype.roomtypename
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setRoomtypename(String roomtypename) {
        this.roomtypename = roomtypename == null ? null : roomtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.price
     *
     * @return the value of roomtype.price
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.price
     *
     * @param price the value for roomtype.price
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.capacity
     *
     * @return the value of roomtype.capacity
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.capacity
     *
     * @param capacity the value for roomtype.capacity
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.bed
     *
     * @return the value of roomtype.bed
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getBed() {
        return bed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.bed
     *
     * @param bed the value for roomtype.bed
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setBed(Integer bed) {
        this.bed = bed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.roomnumber
     *
     * @return the value of roomtype.roomnumber
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.roomnumber
     *
     * @param roomnumber the value for roomtype.roomnumber
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setRoomnumber(Integer roomnumber) {
        this.roomnumber = roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.Booked
     *
     * @return the value of roomtype.Booked
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getBooked() {
        return booked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.Booked
     *
     * @param booked the value for roomtype.Booked
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setBooked(Integer booked) {
        this.booked = booked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.Checkedin
     *
     * @return the value of roomtype.Checkedin
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getCheckedin() {
        return checkedin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.Checkedin
     *
     * @param checkedin the value for roomtype.Checkedin
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setCheckedin(Integer checkedin) {
        this.checkedin = checkedin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.state
     *
     * @return the value of roomtype.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.state
     *
     * @param state the value for roomtype.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.message
     *
     * @return the value of roomtype.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.message
     *
     * @param message the value for roomtype.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}