package com.example.hotel.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
public class Room implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer roomid;
    private  Integer roomtypeid;
    private String roomtypename;
    private  String floorname;

    public String getFloorname() {
        return floorname;
    }

    public void setFloorname(String floorname) {
        this.floorname = floorname;
    }

    public String getRoomtypename() {
        return roomtypename;
    }

    public void setRoomtypename(String roomtypename) {
        this.roomtypename = roomtypename;
    }

    public Integer getRoomtypeid() {
        return roomtypeid;
    }

    public void setRoomtypeid(Integer roomtypeid) {
        this.roomtypeid = roomtypeid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.pic
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomnumber
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String number;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.floorid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private Integer floorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomid
     *
     * @return the value of room.roomid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomid
     *
     * @param roomid the value for room.roomid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.pic
     *
     * @return the value of room.pic
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.pic
     *
     * @param pic the value for room.pic
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.floorid
     *
     * @return the value of room.floorid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public Integer getFloorid() {
        return floorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.floorid
     *
     * @param floorid the value for room.floorid
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setFloorid(Integer floorid) {
        this.floorid = floorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.state
     *
     * @return the value of room.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.state
     *
     * @param state the value for room.state
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.message
     *
     * @return the value of room.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.message
     *
     * @param message the value for room.message
     *
     * @mbggenerated Mon Jan 13 10:05:47 CST 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}